### ISSUE TITLE
"Features" are copied to all blocks in a page

### ISSUE THREAD

**Issue by tomaszn** [EssentialBlocks/price-table-block#6]
Reproduction steps (WordPress 5.8.1, plugin 1.1.3):

1. Create a new page.
2. Add a Columns block, set it to 50/50.
3. Add Price Table to both columns.
4. Change the on any of the Features in the first Price Table.
5. Click on the second Price Table.

Outcome: the new feature caption is copied to the second Price Table.

**Comment by cap340** [comment]
I have the same problem only when duplicating blocks.
I took some time to understand but you have to create a new block for each different price table to prevent the copying of elements.

**Comment by Rahat89** [comment]
@tomaszn We have solved the issue, but still duplicating block have some issues. We are working on that. Hopefully it will be solved in version `1.2.1` release.
